'use client'
import { useEffect, useState } from 'react'

type Account = { id: string; username: string; display_name: string; active: boolean; discount_percent?: number; notes?: string | null; last_login_at?: string | null }
export default function PartnerAccounts({ token, showToast }: { token: string; showToast: (message: string) => void }) {
  const [accounts, setAccounts] = useState<Account[]>([]); const [form, setForm] = useState({ username: '', displayName: '', password: '', discountPercent: '0', notes: '' }); const [loading, setLoading] = useState(true)
  const headers = { 'x-admin-token': token, 'Content-Type': 'application/json' }
  async function load() { const res = await fetch('/api/admin/partner-accounts', { headers }); const data = await res.json(); if (data.success) setAccounts(data.accounts); setLoading(false) }
  useEffect(() => { load() }, [])
  async function create() { const res = await fetch('/api/admin/partner-accounts', { method: 'POST', headers, body: JSON.stringify(form) }); const data = await res.json(); if (!res.ok) return showToast(data.error || '创建失败'); setForm({ username: '', displayName: '', password: '', discountPercent: '0', notes: '' }); showToast('合作伙伴账号已创建'); load() }
  async function toggle(account: Account) { await fetch(`/api/admin/partner-accounts/${account.id}`, { method: 'PATCH', headers, body: JSON.stringify({ active: !account.active }) }); load() }
  async function saveDiscount(account: Account, value: string) { const discountPercent = Math.min(100, Math.max(0, Number(value || 0))); await fetch(`/api/admin/partner-accounts/${account.id}`, { method: 'PATCH', headers, body: JSON.stringify({ discountPercent }) }); showToast('优惠已保存'); load() }
  async function remove(account: Account) { if (!confirm(`删除 ${account.username}？`)) return; await fetch(`/api/admin/partner-accounts/${account.id}`, { method: 'DELETE', headers }); showToast('账号已删除'); load() }
  return <div className="mx-auto max-w-[1180px] px-5 py-7 sm:px-8"><div className="mb-6"><div className="text-[11px] font-bold uppercase tracking-[2px] text-orange">Partner Portal</div><h2 className="mt-1 font-syne text-2xl font-extrabold text-navy">合作伙伴账号</h2><p className="mt-2 text-sm text-muted">创建、停用和分配合作伙伴登录账号。密码不会以明文保存。</p></div><div className="grid gap-5 lg:grid-cols-[360px_1fr]"><section className="rounded-2xl border border-black/10 bg-white p-5"><h3 className="font-bold text-navy">创建新账号</h3><div className="mt-4 space-y-3">{[['username','登录账号'],['displayName','显示名称'],['password','初始密码'],['discountPercent','优惠百分比'],['notes','备注']].map(([key,label]) => <label key={key} className="block text-xs font-bold text-muted">{label}<input type={key === 'password' ? 'password' : key === 'discountPercent' ? 'number' : 'text'} min={0} max={100} value={(form as any)[key]} onChange={e => setForm({ ...form, [key]: e.target.value })} className="mt-1 w-full rounded-lg border border-black/10 px-3 py-2.5 text-sm outline-none focus:border-orange" /></label>)}<p className="text-[11px] text-muted">例如填写 15，合作伙伴看到 15% 优惠价格。</p><button onClick={create} className="w-full rounded-lg bg-orange px-4 py-3 text-sm font-bold text-white">创建账号</button></div></section><section className="space-y-3">{loading ? <div className="rounded-2xl bg-white p-5 text-sm text-muted">加载中…</div> : accounts.length === 0 ? <div className="rounded-2xl bg-white p-5 text-sm text-muted">还没有合作伙伴账号。</div> : accounts.map(account => <div key={account.id} className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-black/10 bg-white p-4"><div><div className="font-bold text-navy">{account.display_name} <span className="ml-2 text-xs font-normal text-muted">@{account.username}</span></div><div className="mt-1 text-xs text-muted">{account.active ? '账号启用中' : '账号已停用'}{account.last_login_at ? ` · 上次登录 ${new Date(account.last_login_at).toLocaleString()}` : ''}</div></div><div className="flex items-center gap-2"><label className="text-xs font-bold text-orange">优惠 <input defaultValue={account.discount_percent || 0} onBlur={e => saveDiscount(account, e.target.value)} type="number" min={0} max={100} className="ml-1 w-16 rounded-lg border border-orange/30 px-2 py-2 text-center text-xs" />%</label><button onClick={() => toggle(account)} className="rounded-lg border border-black/10 px-3 py-2 text-xs font-bold">{account.active ? '停用' : '启用'}</button><button onClick={() => remove(account)} className="rounded-lg border border-red-200 px-3 py-2 text-xs font-bold text-red-600">删除</button></div></div>)}</section></div></div>
}
